# Generated by Django 4.2.5 on 2023-10-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_messages_room_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='messages',
        ),
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.message'),
        ),
    ]
